#!/usr/bin/env sh

ACTUAL_BRIGHTNESS=`cat /sys/class/backlight/intel_backlight/actual_brightness`
MAX_BRIGHTNESS=`cat /sys/class/backlight/intel_backlight/max_brightness`
STEP=305

if [ $# -eq 1 ]; then
  case $1 in
    +)
      SUM=`echo "$ACTUAL_BRIGHTNESS + $STEP" | bc`
      if [ $SUM -lt $MAX_BRIGHTNESS ]; then
        sudo sh -c "echo $SUM > /sys/class/backlight/intel_backlight/brightness"
      else
        sudo sh -c "echo $MAX_BRIGHTNESS > /sys/class/backlight/intel_backlight/brightness"
      fi
    ;;
    -)
      SUM=`echo "$ACTUAL_BRIGHTNESS - $STEP" | bc`
      if [ $SUM -gt 5 ]; then
        sudo sh -c "echo $SUM > /sys/class/backlight/intel_backlight/brightness"
      else
        sudo sh -c "echo 5 > /sys/class/backlight/intel_backlight/brightness"
      fi
    ;;
    *)
    echo "I can't recognize the argument :-("
    ;;
  esac
fi
